[project]
name = "bc_calc"
version = "1.0.0"
description = "DNA Hamming Distance Calculator - A Streamlit app for analyzing DNA sequence similarities"
authors = ["DNA Analysis Team"]
channels = ["conda-forge", "pyviz"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.8"
numpy = ">=1.24.3"
pandas = ">=1.5.3"
streamlit = ">=1.28.0"
plotly = ">=5.15.0"

[tasks]
start = "streamlit run dna_hamming_calculator.py"
install-dev = "pixi install"

[feature.dev.dependencies]
pytest = "*"
black = "*"
flake8 = "*"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }